language: node_js
os: linux
node_js:
  - 10
cache: npm
branches:
  only:
    - master
script:
  - npm run build

deploy:
  edge: true
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: false
  local_dir: dist
  on:
    branch: master
