sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github-token: $GH_TOKEN
  on:
    branch: master
  local-dir: dist
